In [14]:
import pandas as pd

### This combines the csv files generated from Transformer batch processing and merges them with all of the other NLP metrics previously calculated. This merged df is output from this file and used as an input for Classifier ML model training

Fed Data

In [3]:
FED_df = pd.concat(map(pd.read_csv, ['Batch_transformer_files/sentiment_minutes_08_10.csv', 'Batch_transformer_files/sentiment_minutes_10_13.csv','Batch_transformer_files/sentiment_minutes_14_18.csv','Batch_transformer_files/sentiment_minutes2.csv','Batch_transformer_files/sentiment_minutes_22_23.csv']))
USE_scores = pd.read_csv('Batch_transformer_files/use_scores_07_20.csv')
FED_df = FED_df.drop(columns=['Unnamed: 0'])
FED_idx = FED_df['index']
FED_df.reset_index(inplace=True)
FED_df =FED_df.drop(['level_0'],axis=1)
FED_df.to_csv('transformer_sentiment.csv')
FED_df

          index     Score
0    2008-01-30  0.368000
1    2008-03-18  0.333333
2    2008-04-30  0.446352
3    2008-08-05  0.285714
4    2008-09-16  0.323529
..          ...       ...
118  2022-12-14  0.504762
119  2023-02-01  0.500000
120  2023-03-22  0.552941
121  2023-05-03  0.478632
122  2023-06-14  0.878378

[123 rows x 2 columns]

Combine all the Other NLP Data

In [8]:
NLP_data = pd.read_csv('Batch_transformer_files/NLP_output_07_19.csv') # LDA, Cosine Sim, d2V
NER_data = pd.read_csv('Batch_transformer_files/NLP_FOMC_people_07_19.csv') # Named entities 
NLP_data = NLP_data.rename(columns ={'Unnamed: 0': 'index'})
NLP_data['USE_Score'] = USE_scores
NER_data = NER_data.rename(columns ={'Unnamed: 0': 'index'})

# NLP DF Containing all of the NLP Metrics we calculated for the project

In [9]:
NLP_data

,index,cosine_sim,bertopic_num,LDA_1,LDA_2,LDA_3,LDA_4,LDA_5,LDA_6,LDA_7,...,d2v_5,d2v_6,d2v_7,d2v_8,d2v_9,d2v_10,d2v_mean,d2v_umap_first_component,d2v_umap_second_component,USE_Score
0,2008-01-30,0.000000,5,0.313717,0.000119,0.000119,0.392475,0.000119,0.115037,0.178176,...,0.845785,0.499772,-1.271326,-0.753052,-0.015681,1.941257,0.042765,7.422684,0.793003,1.000000
1,2008-03-18,0.647596,2,0.157038,0.318109,0.000091,0.000091,0.000091,0.524301,0.000096,...,-0.169368,0.016397,-0.017338,-0.605733,0.115605,0.875982,0.068234,15.728549,-9.195116,0.849913
2,2008-04-30,0.673309,5,0.518762,0.000057,0.000057,0.073375,0.000057,0.401880,0.005699,...,0.842174,0.483570,-1.342133,-0.865832,0.125346,1.880430,0.103505,7.172862,0.666552,0.860462
3,2008-08-05,0.744683,5,0.010264,0.000147,0.000147,0.490455,0.000147,0.317160,0.181388,...,1.031508,0.717279,-1.597777,-0.848224,-0.222689,1.618246,0.181387,6.871375,-0.629525,0.933642
4,2008-09-16,0.797560,5,0.000160,0.000160,0.000160,0.628175,0.000160,0.335887,0.034976,...,1.061218,0.775751,-1.605029,-1.022294,-0.282534,1.607372,0.215621,7.009882,-0.818085,0.957738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,2022-12-14,0.894163,7,0.010882,0.000097,0.126394,0.200406,0.660115,0.001818,0.000097,...,0.592288,1.090849,0.448520,-1.085123,-1.182336,0.667721,0.107111,15.986513,5.873550,0.949449
119,2023-02-01,0.881633,7,0.023740,0.092348,0.053085,0.502346,0.270380,0.014331,0.000080,...,0.532190,1.077495,0.516067,-0.958908,-1.004091,0.887927,0.063199,15.865612,5.164472,0.955747
120,2023-03-22,0.827124,7,0.028449,0.007872,0.247096,0.058351,0.032967,0.000088,0.000088,...,0.714621,1.306002,0.164022,-0.990384,-1.014638,0.881669,0.149243,16.425026,5.585437,0.947230
121,2023-05-03,0.866951,7,0.012798,0.038760,0.000112,0.154218,0.002981,0.000102,0.000102,...,0.625905,1.203644,0.320048,-0.955947,-1.006802,0.888131,0.124990,16.093105,5.436614,0.955000
122,2023-06-14,0.861132,7,0.001341,0.014304,0.347964,0.604977,0.028569,0.000114,0.000114,...,0.622306,1.173100,0.217708,-1.039295,-1.093128,0.604920,0.128946,16.528090,6.115570,0.950055

Merging the previous NLP data to the Transformer Data which had to be processed separately

In [10]:
# Merge dfs
temp = pd.merge(FED_df,NLP_data, how='left', on = 'index', suffixes = ('_left', '_right'))
df=temp
df

,index,Score,cosine_sim,bertopic_num,LDA_1,LDA_2,LDA_3,LDA_4,LDA_5,LDA_6,...,d2v_5,d2v_6,d2v_7,d2v_8,d2v_9,d2v_10,d2v_mean,d2v_umap_first_component,d2v_umap_second_component,USE_Score
0,2008-01-30,0.368000,0.000000,5,0.313717,0.000119,0.000119,0.392475,0.000119,0.115037,...,0.845785,0.499772,-1.271326,-0.753052,-0.015681,1.941257,0.042765,7.422684,0.793003,1.000000
1,2008-03-18,0.333333,0.647596,2,0.157038,0.318109,0.000091,0.000091,0.000091,0.524301,...,-0.169368,0.016397,-0.017338,-0.605733,0.115605,0.875982,0.068234,15.728549,-9.195116,0.849913
2,2008-04-30,0.446352,0.673309,5,0.518762,0.000057,0.000057,0.073375,0.000057,0.401880,...,0.842174,0.483570,-1.342133,-0.865832,0.125346,1.880430,0.103505,7.172862,0.666552,0.860462
3,2008-08-05,0.285714,0.744683,5,0.010264,0.000147,0.000147,0.490455,0.000147,0.317160,...,1.031508,0.717279,-1.597777,-0.848224,-0.222689,1.618246,0.181387,6.871375,-0.629525,0.933642
4,2008-09-16,0.323529,0.797560,5,0.000160,0.000160,0.000160,0.628175,0.000160,0.335887,...,1.061218,0.775751,-1.605029,-1.022294,-0.282534,1.607372,0.215621,7.009882,-0.818085,0.957738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,2022-12-14,0.504762,0.894163,7,0.010882,0.000097,0.126394,0.200406,0.660115,0.001818,...,0.592288,1.090849,0.448520,-1.085123,-1.182336,0.667721,0.107111,15.986513,5.873550,0.949449
119,2023-02-01,0.500000,0.881633,7,0.023740,0.092348,0.053085,0.502346,0.270380,0.014331,...,0.532190,1.077495,0.516067,-0.958908,-1.004091,0.887927,0.063199,15.865612,5.164472,0.955747
120,2023-03-22,0.552941,0.827124,7,0.028449,0.007872,0.247096,0.058351,0.032967,0.000088,...,0.714621,1.306002,0.164022,-0.990384,-1.014638,0.881669,0.149243,16.425026,5.585437,0.947230
121,2023-05-03,0.478632,0.866951,7,0.012798,0.038760,0.000112,0.154218,0.002981,0.000102,...,0.625905,1.203644,0.320048,-0.955947,-1.006802,0.888131,0.124990,16.093105,5.436614,0.955000
122,2023-06-14,0.878378,0.861132,7,0.001341,0.014304,0.347964,0.604977,0.028569,0.000114,...,0.622306,1.173100,0.217708,-1.039295,-1.093128,0.604920,0.128946,16.528090,6.115570,0.950055

Check to make sure no data is missing/ dates dont match up

In [11]:
missing = FED_df[~FED_df['index'].isin(NLP_data['index'])]
missing # this should be an empty transformer df with no dates inside

Empty DataFrame
Columns: [index, Score]
Index: []

output the final merged NLP df for use in the classification models

In [12]:
df.to_csv('Batch_transformer_files/Full_Fed_Minutes_test_display.csv')